---
title: "Writing Sample (Research Paper)"
format: html
editor: visual
---

## Film Analysis of "Crazy, Stupid, Love"

[Home Page](https://fdf2a4e247794f82859135b6830bd778.app.posit.cloud/file_show?path=%2Fcloud%2Fproject%2FIndex.html)

The following is an analysis of the film "Crazy, Stupid, Love." This paper was nominated for an undergraduate research award.

Romantic comedies are typically viewed as innocent expressions and unique interpretations of a love story and yet they often have exceptionally dark undertones of manipulation. Culture writer for The Atlantic Megan Garber takes this notion a step further, arguing that \"American culture has long been confused about the location of the line between love and violence\" and ultimately romantic comedies \"deserve some of the blame.\" In Nora Ephron\'s classic rom-com You\'ve Got Mail (1998), following their meeting in an online chat room, Kathleen Kelly (Meg Ryan) and Joe Fox (Tom Hanks) become anonymous email correspondents and rival business owners, which Joe discovers just before they are set to meet for the first time. Joe Fox then catfishes his love interest, Kathleen Kelly, online after he has actively worked to run her bookshop into foreclosure. Joe ultimately uses his insider knowledge to his advantage, by inserting himself in Kathleen\'s life under the guise of friendship as he works to poke holes in her rosy mental picture of what her email friend looks like. Joe then alters his email responses to Kathleen to make his cyber alter ego less desirable, hence catfishing her. This film is considered a genre defining romantic comedy, because of its innovative use of the internet to tell a love story but its romanticization of Joe\'s manipulative behaviour towards Kathleen inarguably blurs the line between love and violence just as Garber theorized. 

Thirteen years after You\'ve Got Mail premiered, Glenn Ficarra and John Requa\'s Crazy, Stupid, Love (2011) followed a parallel format of romanticizing male manipulation, fully obscuring the boundary between love and violence through its treatment of the female characters. The film begins with Emily (Julianne Moore) asking her husband Cal Weaver (Steve Carell) for a divorce, and later reveals in a spectacularly awkward car ride that she had an affair with her work friend, David Linhoggen (Kevin Bacon). Cal immediately moves out of the shared family home but finds himself unable to move on emotionally. While drowning his sorrows in alcoholic beverages at a bar and yelling \"My wife fucked David Linhoggen\" to anyone who crosses his path, he garners the pity of womanizer Jacob Palmer (Ryan Gosling). The film follows Jacob\'s attempts to make Cal into a ladies' man and their consequential personality changes along the way. However, there are plot twists woven throughout the film involving Cal\'s children, teenage babysitter Jessica (Analeigh Tipton) who is in love with Cal, and Cal\'s first one-night stand Kate (Marisa Tomei), as they lose their sanity in the pursuit of love. In the film Crazy, Stupid, Love, the male characters frequently reduce the female characters to passive erotic objects through the male gaze and thereby ignore the female characters\' agency.

	However, the popular press\'s response to Crazy, Stupid, Love held a consensus of appreciation for the movie\'s balancing of skepticism and idealization of love. In his review for the New York Times, A.O. Scott argues that the directors managed to \"balance respect for the romantic imperative\... there is lots of soapy, sincere talk of soul mates and endless love --- with a sober acknowledgment of the limits of romanticism.\" Kirk Honeycutt for The Hollywood Reporter highlights that the movie\'s portrayal of three generations falling in love, yet having similar issues, \"demonstrate\[s\] that when it comes to love, experience counts for little.\" Crazy, Stupid, Love was also viewed by the popular press as a comedy full of raw emotion, with consistent praise of its actors \"who let pain seep into the laughs\" according to Peter Travers of Rolling Stone. 

In the scholarly research surrounding Crazy, Stupid, Love there is a distinct focus on the homophobia displayed by Cal and Jacob throughout the film, to emphasize that their relationship is purely platonic. In their cinematic study \"I Love You, Man\" Susan Berridge and Karen Boyle highlight several comments that could be interpreted as homophobic in the film, including when Cal first sees Jacob from across the bar, impeccably dressed and laughing with several women, he crudely concludes Jacob is \"gaaaaay,\" (361). Berridge and Boyle assert that casual homophobic comments such as this one \"follow a well-worn convention of homophobia serving as a cinematic alibi for straight male homosociality,\" meaning the homophobia vindicates that their relationship is platonic (361). David Greven finds a similar trend in his close reading of Crazy, Stupid, Love within his book Ghost Faces Hollywood and Post-Millennial Masculinity. Greven closely reads a scene in when Jacob is naked with his penis in Cal\'s face whilst they are in the gym locker room. In this scene Jacob asks if this display is causing Cal discomfort to which Cal replies that it is making him uncomfortable. Jacob responds \"If you\'re not uncomfortable, Cal, then we got a bigger problem.\" Greven infers that this exchange implies that being gay amounts to an issue and follows the trend of homophobia throughout the movie (30). Jacob then continues to go into a spiel about the importance of being masculine when Cal actually passes out onto Jacob\'s penis. Greven argues that this scene is used to erase the possibility of Cal being sexually interested in Jacob because when faced with Jacob\'s naked body Cal becomes so disinterested he passes into unconsciousness (30). Thus, the friendship between Cal and Jacob is again affirmed to be nothing more than a bromance.

	Other scholars focus on the psychological aspect of Jacob\'s relationship with women in which he uses them as an emotional crutch. In The Jungian Psychology of Cool: Ryan Gosling and the Repurposing of Mid Century Male Rebels, Garrett Hall uses the Jungian terminology of the anima, \"a non-male vehicle through which life can be explored\" to analyze the role women in general play in Jacob\'s life (748). Although the anima is supposed to be one woman, Hall argues that Jacob\'s life is actually driven by women in general as he obsessively orchestrates his persona to attract as many as possible; his character is mostly developed through his flirtatious encounters with women (752). In Christine Spines part review of the film, part interview with the directors of Crazy, Stupid, Love, it is revealed that they had intended to make Jacob unlikeable, slimy even. Jacob would then receive a role reversal later on in the film in which his love interest Hannah (Emma Stone) changes him for the better, but through Gosling\'s insistence and backstory building they resolved for Jacob to be someone the audience would root for from the beginning (Spines 40). Spines asserts that this planning turned Jacob into a metrosexual type who is obsessive about clothing and his physique so he can pick up as many women as possible to thereby avoid emotional vulnerability (40). Thus David Requa (director) argues Jacob would not be viewed as a predator, just someone in desperate need of validation from women of his good looks, falling closely in line with Hall\'s Jungian analysis (Spines 40). 

While scholars have noticed the clear presence of homophobia and Jacob\'s usage of sex as an emotional crutch in Crazy, Stupid, Love, they have failed to note the intensity with which the male gaze impacts the film\'s female characters. Particularly, the popular press and scholarly research presented no criticism of the film\'s treatment of Jessica (the Weaver\'s teenage babysitter) who was written to be in love with Cal, a man in his mid-forties, and repeatedly harassed by Cal\'s son Robbie (Jonah Bobo) after she made it excessively clear she was not interested in him romantically. Woven throughout the film there are other degrading comments made towards women, particularly the pickup artist ploys used by Cal and Jacob. Although the popular press held Crazy, Stupid, Love in high regard for progressively portraying the complexities of falling in love, the tortured awkwardness and romance, I will argue that the film\'s default to the male gaze in its treatment of the female characters is extremely problematic. 

In Laura Mulvey\'s renowned commentary on feminst theory in film \"Visual Pleasure and Narrative Cinema,\" from the book Film Manifestos and Global Cinema Cultures, she situates the male gaze as a tool the audience involuntarily uses while viewing a film (365). Mulvey argues that \"in a world ordered by sexual imbalance, pleasure in looking has been split between active/male and passive/female,\" (364). This idea of women being a passive object for men to pursue is endemic to the romantic comedy genre, but Mulvey takes this idea a step further arguing that the function of women in film is simply to be looked at and desired by male characters, to have an erotic impact (364). Essentially, under the brunt force of the male gaze, Mulvey insinuates that the only value female characters can contribute to a film are the actions they provoke in the male characters, what they inspire the heroes to do (366).
