---
title: "Writing Sample (Research Paper)"
format: html
editor: visual
---

## Film Analysis of "Crazy, Stupid, Love"

The following is an analysis of the film "Crazy, Stupid, Love." This paper was nominated for an undergraduate research award.

Romantic comedies are typically viewed as innocent expressions and unique interpretations of a love story and yet they often have exceptionally dark undertones of manipulation. Culture writer for The Atlantic Megan Garber takes this notion a step further, arguing that \"American culture has long been confused about the location of the line between love and violence\" and ultimately romantic comedies \"deserve some of the blame.\" In Nora Ephron\'s classic rom-com You\'ve Got Mail (1998), following their meeting in an online chat room, Kathleen Kelly (Meg Ryan) and Joe Fox (Tom Hanks) become anonymous email correspondents and rival business owners, which Joe discovers just before they are set to meet for the first time. Joe Fox then catfishes his love interest, Kathleen Kelly, online after he has actively worked to run her bookshop into foreclosure. Joe ultimately uses his insider knowledge to his advantage, by inserting himself in Kathleen\'s life under the guise of friendship as he works to poke holes in her rosy mental picture of what her email friend looks like. Joe then alters his email responses to Kathleen to make his cyber alter ego less desirable, hence catfishing her. This film is considered a genre defining romantic comedy, because of its innovative use of the internet to tell a love story but its romanticization of Joe\'s manipulative behaviour towards Kathleen inarguably blurs the line between love and violence just as Garber theorized. 

Thirteen years after You\'ve Got Mail premiered, Glenn Ficarra and John Requa\'s Crazy, Stupid, Love (2011) followed a parallel format of romanticizing male manipulation, fully obscuring the boundary between love and violence through its treatment of the female characters. The film begins with Emily (Julianne Moore) asking her husband Cal Weaver (Steve Carell) for a divorce, and later reveals in a spectacularly awkward car ride that she had an affair with her work friend, David Linhoggen (Kevin Bacon). Cal immediately moves out of the shared family home but finds himself unable to move on emotionally. While drowning his sorrows in alcoholic beverages at a bar and yelling \"My wife fucked David Linhoggen\" to anyone who crosses his path, he garners the pity of womanizer Jacob Palmer (Ryan Gosling). The film follows Jacob\'s attempts to make Cal into a ladies' man and their consequential personality changes along the way. However, there are plot twists woven throughout the film involving Cal\'s children, teenage babysitter Jessica (Analeigh Tipton) who is in love with Cal, and Cal\'s first one-night stand Kate (Marisa Tomei), as they lose their sanity in the pursuit of love. In the film Crazy, Stupid, Love, the male characters frequently reduce the female characters to passive erotic objects through the male gaze and thereby ignore the female characters\' agency.

	However, the popular press\'s response to Crazy, Stupid, Love held a consensus of appreciation for the movie\'s balancing of skepticism and idealization of love. In his review for the New York Times, A.O. Scott argues that the directors managed to \"balance respect for the romantic imperative\... there is lots of soapy, sincere talk of soul mates and endless love --- with a sober acknowledgment of the limits of romanticism.\" Kirk Honeycutt for The Hollywood Reporter highlights that the movie\'s portrayal of three generations falling in love, yet having similar issues, \"demonstrate\[s\] that when it comes to love, experience counts for little.\" Crazy, Stupid, Love was also viewed by the popular press as a comedy full of raw emotion, with consistent praise of its actors \"who let pain seep into the laughs\" according to Peter Travers of Rolling Stone. 

In the scholarly research surrounding Crazy, Stupid, Love there is a distinct focus on the homophobia displayed by Cal and Jacob throughout the film, to emphasize that their relationship is purely platonic. In their cinematic study \"I Love You, Man\" Susan Berridge and Karen Boyle highlight several comments that could be interpreted as homophobic in the film, including when Cal first sees Jacob from across the bar, impeccably dressed and laughing with several women, he crudely concludes Jacob is \"gaaaaay,\" (361). Berridge and Boyle assert that casual homophobic comments such as this one \"follow a well-worn convention of homophobia serving as a cinematic alibi for straight male homosociality,\" meaning the homophobia vindicates that their relationship is platonic (361). David Greven finds a similar trend in his close reading of Crazy, Stupid, Love within his book Ghost Faces Hollywood and Post-Millennial Masculinity. Greven closely reads a scene in when Jacob is naked with his penis in Cal\'s face whilst they are in the gym locker room. In this scene Jacob asks if this display is causing Cal discomfort to which Cal replies that it is making him uncomfortable. Jacob responds \"If you\'re not uncomfortable, Cal, then we got a bigger problem.\" Greven infers that this exchange implies that being gay amounts to an issue and follows the trend of homophobia throughout the movie (30). Jacob then continues to go into a spiel about the importance of being masculine when Cal actually passes out onto Jacob\'s penis. Greven argues that this scene is used to erase the possibility of Cal being sexually interested in Jacob because when faced with Jacob\'s naked body Cal becomes so disinterested he passes into unconsciousness (30). Thus, the friendship between Cal and Jacob is again affirmed to be nothing more than a bromance.

	Other scholars focus on the psychological aspect of Jacob\'s relationship with women in which he uses them as an emotional crutch. In The Jungian Psychology of Cool: Ryan Gosling and the Repurposing of Mid Century Male Rebels, Garrett Hall uses the Jungian terminology of the anima, \"a non-male vehicle through which life can be explored\" to analyze the role women in general play in Jacob\'s life (748). Although the anima is supposed to be one woman, Hall argues that Jacob\'s life is actually driven by women in general as he obsessively orchestrates his persona to attract as many as possible; his character is mostly developed through his flirtatious encounters with women (752). In Christine Spines part review of the film, part interview with the directors of Crazy, Stupid, Love, it is revealed that they had intended to make Jacob unlikeable, slimy even. Jacob would then receive a role reversal later on in the film in which his love interest Hannah (Emma Stone) changes him for the better, but through Gosling\'s insistence and backstory building they resolved for Jacob to be someone the audience would root for from the beginning (Spines 40). Spines asserts that this planning turned Jacob into a metrosexual type who is obsessive about clothing and his physique so he can pick up as many women as possible to thereby avoid emotional vulnerability (40). Thus David Requa (director) argues Jacob would not be viewed as a predator, just someone in desperate need of validation from women of his good looks, falling closely in line with Hall\'s Jungian analysis (Spines 40). 

	While scholars have noticed the clear presence of homophobia and Jacob\'s usage of sex as an emotional crutch in Crazy, Stupid, Love, they have failed to note the intensity with which the male gaze impacts the film\'s female characters. Particularly, the popular press and scholarly research presented no criticism of the film\'s treatment of Jessica (the Weaver\'s teenage babysitter) who was written to be in love with Cal, a man in his mid-forties, and repeatedly harassed by Cal\'s son Robbie (Jonah Bobo) after she made it excessively clear she was not interested in him romantically. Woven throughout the film there are other degrading comments made towards women, particularly the pickup artist ploys used by Cal and Jacob. Although the popular press held Crazy, Stupid, Love in high regard for progressively portraying the complexities of falling in love, the tortured awkwardness and romance, I will argue that the film\'s default to the male gaze in its treatment of the female characters is extremely problematic. 

	In Laura Mulvey\'s renowned commentary on feminst theory in film \"Visual Pleasure and Narrative Cinema,\" from the book Film Manifestos and Global Cinema Cultures, she situates the male gaze as a tool the audience involuntarily uses while viewing a film (365). Mulvey argues that \"in a world ordered by sexual imbalance, pleasure in looking has been split between active/male and passive/female,\" (364). This idea of women being a passive object for men to pursue is endemic to the romantic comedy genre, but Mulvey takes this idea a step further arguing that the function of women in film is simply to be looked at and desired by male characters, to have an erotic impact (364). Essentially, under the brunt force of the male gaze, Mulvey insinuates that the only value female characters can contribute to a film are the actions they provoke in the male characters, what they inspire the heroes to do (366).

After the dissolution of his marriage, Cal befriends womanizer Jacob Palmer, who makes it his mission to turn Cal into the ultimate ladies man through pickup artists ploys designed to manipulate women into sex, depriving them of their agency. This process involves Jacob having Cal watch him pick up women at a bar over a period of time until Cal recognizes his methodical pattern for attracting women, because Jacob acts as if picking up women is a sport. There is a full montage of beautiful women who receive almost no characterization beyond the fact that they inspire lust in Jacob. However, Jacob\'s overall methodology for picking up women is revealed in this scene; it involves first buying the woman in question a drink, even if she does not want one, then asking the woman many questions \"to put the impetus on her, she has to be the interesting one,\" in order to capture their attention. Cal actually remarks that Jacob\'s pick up artist process is nothing more than \"a creepy game\" but he follows along nonetheless. Whilst Jacob is making sure Cal understands every step in his process, Cal recounts the most problematic step: he does not ask the women if they want to go home with him. Jacob always tells the women \"let\'s get out of here\" which Cal interprets so that the women \"have no choice in the matter, it is \[Jacob\'s\] choice and they are so overjoyed to have had the opportunity to make sweet, sweet love to \[Jacob\].\" Women are portrayed by this film as passive objects as they are relegated to role of the pursued, with no agency, and given no purpose outside of their erotic impact on the male characters. 

Unfortunately in Crazy, Stupid, Love, the female characters also situate their own self importance around their physical attractiveness, defining themselves by their erotic impact on men. After reciting Jacob\'s flirtatious process perfectly, Jacob determines that Cal is ready to pick up a woman at the bar and directs him towards Kate. The pick up methodology fails very quickly once it is revealed that Kate is an alcoholic and she actually wants to get know Cal before having sex with him. She unexpectedly turns the tables on Cal, asking him what he does for a living which he in turn tries to deflect, quickly making Kate very uncomfortable. Eventually, he blurts out his entire life\'s story including his separation from his wife, her affair, and that he has children but the only information Kate retains from his rant is that Cal thinks she is \"the perfect combination of sexy and cute\". In this scene Kate situates her own self importance around her sexual appeal to a man, giddy at being objectified, disregarding several warning signs that highlight Cal as emotionally unavailable, particularly his remaining feelings for his ex-wife. The male gaze is made all the more insidious here because it is the female character who focuses on her erotic impact on the male character, rather than just the male character noting her physical attractiveness. Kate is so moved by this sentiment that she goes home with Cal to his apartment and they proceed to kiss passionately. Kate asks Cal what is on his mind and he replies he wants \"to show \[Kate\] off to \[his\] ex-wife and make her really jealous\". This comment inspires a great deal of excitement in Kate as she begins to shriek with joy and leaps on top of Cal; the scene then cuts to the morning after and it is left to the audience to assume that they had sex. Cal tells Kate point blank that he plans to use her to make his wife jealous and yet she expresses gratitude for being a tool of manipulation. The male gaze may function as a compliment in this scene, but it is just as damaging because it reinforces that Kate\'s sole purpose is her erotic impact on Cal, that her physical appearance is her only true virtue.

Although the pickup artist techniques failed to work with Kate, the other women Cal pursues in this film are framed as easily manipulated and exchangeable for one another. Following his first one-night stand with Kate, Cal goes back to the bar where they met, dressed in an immaculate suit, as the film enters a montage of different women for him to flirt with and eventually take home, using Jacob\'s patented phrase \"let's get out of here.\" In this scene fluid jump cuts are used to transition from woman to woman, each barely having any dialogue, blending them together into a sea of visual pleasure for Cal to take in. The women in this film are yet again portrayed as passive objects, for the male characters to derive pleasure from, but this scene makes them seem interchangeable. As if the women\'s physical and sexual attractiveness is the only trait worth portraying and that ultimately, it makes them indistinguishable from one another.

Meanwhile, the character of young Robbie relentlessly pursuing Jessica highlights the refusal to recognize women\'s agency and the desire to constantly objectify women is endemic to both boys and men. In the very beginning of the film, 17 year old Jessica walks in on 13 year old Robbie Weaver, the boy she is babysitting, masturbating. Jessica attempts to brush off this awkward scenario and claims she did not see anything to which Robbie responds \"for the record: I think about you while I do it,\" profusely objectifying her. As Robbie then attempts to confess his love for Jessica she repeatedly protests and tells him that he is being inappropriate but he does not stop until his parents show up. This scene sets the stage for Jessica to be viewed as an object of pleasure as she is quite literally being used as an object for pleasure, hence she serves an erotic impact. This scene is a precursor to the recurring theme of men (boys in this case) actively pursuing women who are framed as passive. No means no is a message that is never uttered throughout the film as Robbie continuously pursues Jessica in spite of constant rejection. Robbie even goes as far as creating a public display at Jessica\'s school, declaring his love for her in the courtyard to which she kindly but continuously tells him that he must stop. Robbie and Cal later have a brief conversation about Robbie being in love with someone who wants someone else but Cal tells him \"well you can\'t just give up.\" Although Cal does not know who Robbie has romantic feelings for, he consistently urges his son to pursue someone who has made it exceedingly clear that she has no interest in him. Women are thus relegated to the role of the passive prize to be pursued and men (or boys in Robbie\'s case) are the active pursuers just as Mulvey theorized. 

Mulvey also emphasizes the cyclical nature of the male gaze because \"traditionally, the woman displayed has functioned on two levels: as erotic object for the characters within the screen story, and as erotic object for the spectator within the auditorium,\" (364). Unfortunately, 17 year old Jessica fulfills both of these roles within Crazy, Stupid, Love. After hearing from her parents that Cal has been very sexually active and is \"a real ladies man,\" Jessica goes to a sexually active girl at her school for advice on how to get Cal to notice her. The girl convinces her that the only way to get herself on Cal\'s radar is to take nude photos to \"force his hand. Make him unable to stop himself from doing what he knows to be wrong.\" This scene is particularly problematic because it insinuates that upon seeing a nude photo of a young girl, a man would have no other option than to have sex with her. It becomes even more problematic from there onward when Jessica takes nude photos of herself with the intention of giving them to Cal. Thus, she has produced and will eventually distribute child pornography. The schoolgirl trope is a well-recognized male fantasy, and here it meets Mulvey\'s dual function of a woman under the male gaze: Jessica takes naked photos of herself to please a male she is interested in but it also panders to the male audience, fulfilling their fantasy. 

Jessica\'s role as an object of pleasure does not end after she takes the photos, but actually comes full circle under the male gaze. Ultimately, the child pornography never makes its way to Cal because Jessica\'s parents find it. She instead gives them to Robbie as a combined graduation present and consolation prize for rebuffing his affection. This final note to Jessica and Robbie\'s relationship involves Robbie claiming he has no plans of giving up on Jessica, he just plans to pursue her when he is older; Jessica then presents him with the pornographic photos, much to his pleased shock and gives him a kiss on the cheek before saying goodbye. Throughout the film Jessica rejects Robbie\'s inappropriate displays of affection and yet at the very end of the film she has become worn down by his persistence and rewards his toxic behaviour, pleasing him by again fulfilling the role of an object of visual pleasure. Jessica\'s storyline in Crazy, Stupid, Love highlights the general and recuring issue with the male gaze: the female characters act and exist to please the male characters and the male audience.

The dangers of sending this message to a predominantly female audience are numerous but the most concerning is the potential for them to internalize this subliminal messaging that their worth is tied to their physical appeal to men. Famous for their work in the intersection of psychology and feminism, Barbara Fredrickson and Tomi-Ann Roberts define sexual objectification as asserting another person\'s primary value comes from their physical or sexual attractiveness (175). However, Fredrickson and Roberts take the damage of sexual objectification a step further in their study \"Objectification Theory: Toward Understanding Women\'s Lived Experiences and Mental Health Risks,\" arguing it has consequences across the lifespan of women. They are particularly concerned about the development of self-objectification, a process by which women and girls develop a third-person perspective of their body and place chronic attention on their own physical appearance, believing their value is derived from their sexual appeal (Fredrickson and Roberts 173). Fredrickson and Roberts believe that the overexposure of women to sexual objectification and the corresponding development of self-objectification ultimately contribute to \"an array of mental health risks that disproportionately affect women: unipolar depression, sexual dysfunction, and eating disorders,\" (173).

Crazy, Stupid, Love\'s unwavering focus of the male gaze holds the potential to harm female viewers by exposing them to relentless sexual objectification of the female characters, constantly signaling to the audience that the only value the female characters bring is their physical and sexual appeal. Any woman in the audience watching the storyline of Jessica unravel throughout the film, from her self-sexualizing to get Cal\'s attention to Robbie\'s borderline harassment tactics to win her over, is at a heightened risk of developing self-objectification mechanisms. With each problematic instance of the male gaze in this film, their bodily perception could become twisted to the point of which they are left hopelessly wondering whether the directors were correct in insinuating that their only value as a young woman is derived from their physical attractiveness. Thus, the film Crazy, Stupid, Love poses an undeniable threat to the mental and physical health of women through its sexual objectification of the female characters and by extension the female audience.

	This default to the male gaze exists far beyond the realm of fiction and has long lasting mental health consequences for its female survivors. On January 16, 1998 it was revealed in a court document for the first time that the President of the United States, Bill Clinton, had been having an affair with White House intern, Monica Lewinksy. To say there was a power imbalance between the two, even disregarding their 27 year age gap, would be the understatement of the 1990s. Instead of being treated as a victim of sexual misconduct, 24 year old Monica Lewinsky was lambasted by the mainstream media, who overly sexualized her from posting the most intimate details of her previous sex life to framing her as the initiator of the relationship (Everbach 268). In an analysis of 175 articles that were written about the Lewinsky-Clinton scandal, Tracy Everbach found that Lewinsky was \"portrayed solely in the context of her association with men\" and described as \"a naïve intern, a sexual predator, or a jealous girlfriend,\" by the media with many articles commenting on her physical attractiveness, and even fat-shaming her (277). Everbach is quick to point out that all of these frames were set by reporters and acquaintances of Lewinsky, majority of whom were men, effectively silencing her voice and reducing her to a passive, sexualized object (277). Years later, Monica Lewinsky was diagnosed with Post Traumatic Stress Disorder due to the humiliation she experienced from the media\'s obsession with her sex life and physical appearance. She claims she will never be completely healed from the pain these overly sexualized narratives inflicted upon her (Lewinsky). The mainstream media has immense power over its female viewers by objectifying women and ignoring their agency, as displayed in the case of Monica Lewinsky and it continues to use these tactics against women to this very day.

\
\
\
\
\
\
\

Works Cited

Berridge, Susan, and Karen Boyle. \"I Love You, Man.\" Feminist Media Studies, vol. 14, no. 3, 2014, pp. 353-368, Taylor & Francis Online, DOI: [10.1080/14680777.2012.740494](https://doi.org/10.1080/14680777.2012.740494)

Crazy, Stupid, Love. Directed by Glenn Ficarra and John Requa, performances by Steve Carrell, Ryan Gosling, Julianne Moore, Emma Stone, Analeigh Tipton, Marisa Tomei, and Jonah Bobo, Carousel Productions, 2011.

Everbach, Tracy. \"Monica Lewinsky and Shame: 1998 Newspaper Framing of \'That Woman.\'\" Journal of Communication Inquiry, vol. 41, no. 3, 2017, pp. 268--287. SAGE Publications, DOI:10.1177/0196859917707920.

Fredrickson, Barbara, and Tomi-Ann Roberts. \"Objectification Theory: Toward Understanding Women\'s Lived Experiences and Mental Health Risks.\" Psychology of Women Quarterly, vol. 21, no. 2, 1997, pp. 173--206. Wiley Online Library, DOI:10.1111/j.1471-6402.1997.tb00108.x 

Garber, Megan. \"How Rom-coms Distort Romance.\" The Atlantic, 2 November 2016, www.theatlantic.com/entertainment/archive/2016/11/its-rom-coms-fault-too/505928/

Greven, David. Ghost faces: Hollywood and Post-Millennial Masculinity. Albany, New York: State University of New York Press, 2016.

Hall, Garret. \"The Jungian Psychology of Cool: Ryan Gosling and the Repurposing of Mid Century Male Rebels.\" 2013. Northern Illinois University, Undergraduate thesis.

Honeycutt, Kirk. \"Crazy, stupid, love: Film review.\" The Hollywood Reporter, 30 November 2012,  www.hollywoodreporter.com/review/crazy-stupid-love-film-review-214009. 

Lewinsky, Monica. \"Monica Lewinsky: Emerging from "the House of Gaslight" in the Age of #metoo.\" Vanity Fair, 25 February 2018, www.vanityfair.com/news/2018/02/monica-lewinsky-in-the-age-of-metoo. 

Mulvey, Laura. \"Visual Pleasure and Narrative Cinema.\" Film Manifestos and Global Cinema Cultures: A Critical Anthology, edited by Scott MacKenzie, University of California Press, 2014, pp 359-370.

Scott, A.O. \"What's a guy to do if his wife cheats on him? Head to the mall.\" The New York Times. 29 July 2011, www.nytimes.com/2011/07/29/movies/crazy-stupid-love-with-steve-carell-review.html. 

Spines, Christine. \"Fools for Love.\" Film Comment, vol. 47, no. 4, 2011, pp. 38--41. JSTOR, www.jstor.org/stable/43458023. 

Travers, Peter. \"Crazy Stupid Love.\" Rollingstone. 28 July 2011, www.rollingstone.com/movies/movie-reviews/crazy-stupid-love-126965/. 

You\'ve Got Mail. Directed by Nora Ephron, performances by Tom Hanks and Meg Ryan, Warner Brothers, 1998.

\

## 
